### ISSUE TITLE
Responses should not always return an array

### ISSUE THREAD

**Issue by summera** [inf0rmer/blanket#21]
referencing https://github.com/inf0rmer/blanket/pull/15

@inf0rmer  Let me start by saying this gem is awesome and has given me some really great ideas for things to build recently!

In my opinion Blanket should not force responses into an array. If I make a request to `http://www.example.com/users/1`, I am expecting a single hash (which most closely resembles a JSON object) at the root of the response describing this resource. Having Blanket force this single object into an array (which most closely resembles a JSON array) seems a bit odd. 

If you are following common JSON API conventions (http://jsonapi.org/format/#document-structure-top-level), it is standard to have a JSON object (which would map to a hash in our case) at the root of every JSON API response. Taking all responses (which are more often than not a JSON object) and wrapping them in an array doesn't seem like a good approach to bake into this awesome gem.

If some users of Blanket need all their responses in an array, they can of course, do so with little effort. Blanket, in my opinion, shouldn't change the response conventions chosen by services; this should be left to the user of the gem and be done with coercion after the fact to fit their use case.

**Comment by ianks** [comment]
I agree. This behavior is totally unexpected an unconventional. I would agree with @summera that mandating use of an array is a bad idea, and it would probably be better to follow some sort of convention i.e. JSON API.

**Comment by michaelachrisco** [comment]
+1

**Comment by Incanus3** [comment]
+1

**Comment by inf0rmer** [comment]
Hello everyone! This was how it was before, and then it was changed because of feedback. I think the response is now overwhelmingly against it, so I'll revert the change soon. Thanks!

**Comment by inf0rmer** [comment]
I've published version `3.0.0`, where this issue is fixed. Thanks for all the comments!
