### ISSUE TITLE
put method request action should allow a curl -d style data payload

### ISSUE THREAD

**Issue by jasonm23** [inf0rmer/blanket#27]
Provide data as RecursiveOpenStruct preferably. (or fall back to hash)

**Comment by jasonm23** [comment]
Ah, I use `:body` option ?

**Comment by jasonm23** [comment]
Yes I can.

**Comment by inf0rmer** [comment]
Happy it worked out for you! :smile:

**Comment by jasonm23** [comment]
Thanks, I really like this gem.  Put could use a spot of doc in the README, I will fork and add it for you.
